<?php

$title = 'User Edit';

$this->headTitle($title);

 ?>

 <h1><?=$this->escapeHtml($title)?></h1>

<?php

$form->setAttribute('action', $this->url('user', ['action' => 'edit','id' => $id]));
$form->prepare();
?>

<?php
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));

?>
<br>
<?php
echo $this->formRow($form->get('first_name'));
?>
<br>
<br>

<?php
echo $this->formRow($form->get('last_name'));
?>
<br>
<br>
<?php
echo $this->formRow($form->get('policy_no'));
?>
<br>
<br>
<?php
echo $this->formRow($form->get('start_date'));
?>
<br>
<br>
<?php
echo $this->formRow($form->get('end_date'));
?>
<br>
<br>
<?php
echo $this->formRow($form->get('premium'));
?>
<br>
<br>
<?php
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
